[[shades]]
name = "vibrance"
default = true  # will be activated when no other shader is scheduled

[[shades]]
name = "blue-light-filter"
start_time = 18:00:00
end_time = 06:00:00   # optional if more than one shader has start_time
